package validation;

public enum ValidationStatus {
    EXECUTION_ERROR,
    SUCCESS,
    INVALID_OBJECT,
    INVALID_ARGUMENTS,
    INVALID_ID,
    INVALID_USER_DATA,
    USER_ALREADY_EXISTS,
    REGISTRATION_ERROR,
    NOT_ENOUGH_ARGUMENTS,
    INPUT_REQUIRED,
    NOT_RECOGNIZED
}
