spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/islab1_db
        username: islab1_user
        password: pass
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            jakarta:
                persistence:
                    schema-generation:
                        database:
                            action: update
        open-in-view: false

logging:
    level:
        ru.mip3x: DEBUG