@startuml

package "pokemons" {
    Class Budew {
        +Budew(String name, int level)
    }
    Class Hitmonchan {
        +Hitmonchan(String name, int level)
    }
    Class Kyurem {
        +Kyurem(String name, int level)
    }
    Class Roselia {
        +Roselia(String name, int level)
    }
    Class Roserade {
        +Roserade(String name, int level)
    }
    Class Tyrogue {
        +Tyrogue(String name, int level)
    }
}

class Pokemon

Pokemon <-- Hitmonchan
Pokemon <-- Kyurem
Pokemon <-- Roselia
Pokemon <-- Roserade
Pokemon <-- Tyrogue

@enduml