name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
      
    - name: Build 'server.jar'
      working-directory: ./second-course/web/lab1/backend
      run: ./gradlew build

    - name: Copy 'server.jar' to webapp
      run: |
        mkdir -p webapp/fcgi-bin
        cp second-course/web/lab1/backend/build/libs/*.jar webapp/fcgi-bin/server.jar

    - name: Copy frontend to webapp
      run: |
        mkdir -p webapp
        cp -r second-course/web/lab1/frontend/* webapp/

    - name: Rsync to the server
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr
        path: ./webapp/
        remote_path: /home/studs/${{ secrets.SSH_USER }}/web/lab1/webapp/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.SSH_PORT }}

    - name: Manage processes on server
      run: |
        mkdir ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/actions
        chmod 600 /tmp/actions
        ssh -i /tmp/actions -p ${{ secrets.SSH_PORT }} -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          USER_HOME="/home/studs/${{ secrets.SSH_USER }}"
          LOG_FILE="\$USER_HOME/web/lab1/httpd-root/logs/deploy.logs"

          # Stop existing HTTPD processes
          killall httpd >> \$LOG_FILE 2>&1 || echo "No HTTPD processes found" >> \$LOG_FILE

          # Start HTTPD
          httpd -f \$USER_HOME/web/lab1/httpd-root/conf/httpd.conf -k start >> \$LOG_FILE 2>&1

          # Stop existing Java processes
          killall java >> \$LOG_FILE 2>&1 || echo "No Java processes found" >> \$LOG_FILE

          # Start Java application
          java -DFCGI_PORT=41489 -jar \$USER_HOME/web/lab1/webapp/fcgi-bin/server.jar >> \$LOG_FILE 2>&1 &
        EOF

