name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
      
    - name: Build 'server.jar'
      working-directory: ./second-course/web/lab1/backend
      run: ./gradlew build

    - name: Copy 'server.jar' to webapp
      run: |
        mkdir -p webapp/fcgi-bin
        cp second-course/web/lab1/backend/build/libs/*.jar webapp/fcgi-bin/server.jar

    - name: Copy frontend to webapp
      run: |
        mkdir -p webapp
        cp -r second-course/web/lab1/frontend/* webapp/

    - name: Rsync to the server
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr
        path: ./webapp/
        remote_path: /home/studs/${{ secrets.SSH_USER }}/web/lab1/webapp/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.SSH_PORT }}

    - name: Manage processes on server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            ls -al
            cat test
