name: Tests

on:
  push:
    branches: [ "feature/information-system-lab-1" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew --no-daemon test

      - name: Mark as success
        if: ${{ success() }}
        run: |
          echo "[Tests passed]" >> $GITHUB_STEP_SUMMARY

      - name: Mark as failed
        if: ${{ failure() }}
        run: |
          echo "[Tests failed]" >> $GITHUB_STEP_SUMMARY
